version: 2.1
parameters:
  image-tag:
    type: string
    default: "latest"
  package-name:
    type: string
    default: "service-example"
  stage:
    type: string
    default: "qa"
  sha:
    type: string
    default: ""
  branch:
    type: string
    default: ""
  tag:
    type: string
    default: ""
jobs:
  build:
    docker:
      - image: circleci/node:latest
    environment:
      PACKAGE_NAME: << pipeline.parameters.package-name >>
      SHA: << pipeline.parameters.sha >>
      TAG: << pipeline.parameters.tag >>
      BRANCH: << pipeline.parameters.branch >>
    steps:
      - run: echo ${PACKAGE_NAME}
      - run: echo ${SHA}
      - run: echo ${TAG}
      - run: echo ${BRANCH}
