version: 2.1
parameters:
  image-tag:
    type: string
    default: "latest"

jobs:
  build:
    docker:
      - image: circleci/node:<< pipeline.parameters.image-tag >>
    environment:
      IMAGE_TAG: << pipeline.parameters.image-tag >>
    steps:
      - run: echo "Image tag used was ${IMAGE_TAG}"
