version: 2.1
parameters:
  image-tag:
    type: string
    default: "latest"
  package-name:
    type: string
    default: "service-example"
  stage:
    type: string
    default: "qa"
jobs:
  build:
    docker:
      - image: circleci/node:<< pipeline.parameters.image-tag >>
    environment:
      STAGE: << pipeline.parameters.stage >>
      PACKAGE_NAME: << pipeline.parameters.package-name >>
      IMAGE_TAG: << pipeline.parameters.image-tag >>
    steps:
      - run: echo ${IMAGE_TAG}
      - run: echo ${PACKAGE_NAME}
      - run: echo ${STAGE}
