version: 2.1
parameters:
  image-tag:
    type: string
    default: "latest"
  package-name:
    type: string
    default: "service-example"
  stage:
    type: string
    default: "stage"
jobs:
  build:
    docker:
      - image: circleci/node:<< pipeline.parameters.image-tag >>
    environment:
      STAGE: << pipeline.parameters.stage >>
      PACKAGE_NAME: << pipeline.parameters.package-name >>
    steps:
      - run: echo "Params passed:"
      - run: echo "STAGE: ${STAGE}"
      - run: echo "PACKAGE NAME: ${PACKAGE_NAME}"
